// Generated by CoffeeScript 1.10.0
(function() {
  var assert, should;

  should = require('should');

  assert = require('assert');

  describe('Unit Tests', function() {
    return it('TODO:: Write unit tests', function(done) {
      assert(true);
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=no_tests.js.map
