// Generated by CoffeeScript 1.10.0
(function() {
  var _;

  _ = require('lodash');

  module.exports = function(app, resources, spec, config) {
    var definitions, paths, specification;
    if (spec == null) {
      spec = '/spec';
    }
    paths = {};
    definitions = {};
    _.each(resources, function(resource) {
      var swagger;
      swagger = resource.swagger();
      if ((swagger.paths["/routes"] != null)) {
        swagger.paths["/routes"].get.parameters.push({
          name: 'query',
          "in": 'query',
          description: 'Query by example. Pass a JSON object to find, for example: {"to": "313"}.',
          type: 'string',
          required: false,
          "default": ''
        });
      }
      if ((swagger.paths["/nodetypes/{nodesType}/nodes"] != null)) {
        swagger.paths["/nodetypes/{nodesType}/nodes"].get.parameters.push({
          name: 'query',
          "in": 'query',
          description: 'Query by example. Pass a JSON object or where clause string to find. JSON example: {"postalCode": "60440", "name": "BDWP IL - Bolingbrook"}  Where Clause Example: "n.postalCode  = \'60440\' and n.name = \'BDWP IL - Bolingbrook\'" (include the quotes).',
          type: 'string',
          required: false,
          "default": ''
        });
      }
      if ((swagger.paths["/edgetypes/{edgesType}/edges"] != null)) {
        swagger.paths["/edgetypes/{edgesType}/edges"].get.parameters.push({
          name: 'query',
          "in": 'query',
          description: 'Query by example. Pass a JSON object or where clause string to find. JSON example: {"id": "2000507_2000819"}  Where Clause Example: "toInt(e.leadTime)>2 and toInt(e.sellerCost)=0" (include the quotes).',
          type: 'string',
          required: false,
          "default": ''
        });
      }
      paths = _.assign(paths, swagger.paths);
      return definitions = _.assign(definitions, swagger.definitions);
    });
    specification = {
      swagger: '2.0',
      info: {
        description: 'Network Persister',
        version: config.version,
        title: 'Network Persister',
        contact: {
          name: 'Build Direct'
        }
      },
      host: config.host,
      basePath: config.basepath,
      schemes: [config.scheme],
      definitions: definitions,
      paths: paths
    };
    return app.get(spec, function(req, res, next) {
      return res.json(specification);
    });
  };

}).call(this);

//# sourceMappingURL=swagger.js.map
