// Generated by CoffeeScript 1.10.0
(function() {
  var iGraphRepository;

  iGraphRepository = (function() {
    function iGraphRepository(config) {}

    iGraphRepository.prototype.query = function(query) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.getNode = function(id) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.setNode = function(id, json) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.deleteNode = function(id, type) {
      if (type == null) {
        type = 'node';
      }
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.getRelationship = function(id) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.setRelationship = function(id, json) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.deleteRelationship = function(id) {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.pipeline = function() {
      throw new Error("not implemented");
    };

    iGraphRepository.prototype.exec = function(callback) {
      throw new Error("not implemented");
    };

    return iGraphRepository;

  })();

  module.exports = iGraphRepository;

}).call(this);

//# sourceMappingURL=iGraphRepository.js.map
