// Generated by CoffeeScript 1.10.0
(function() {
  var iRepository;

  iRepository = (function() {
    function iRepository(config) {}

    iRepository.prototype.find = function(query) {
      throw new Error("not implemented");
    };

    iRepository.prototype.get = function(id) {
      throw new Error("not implemented");
    };

    iRepository.prototype.add = function(json) {
      throw new Error("not implemented");
    };

    iRepository.prototype.set = function(id, json) {
      throw new Error("not implemented");
    };

    iRepository.prototype["delete"] = function(id) {
      throw new Error("not implemented");
    };

    iRepository.prototype.pipeline = function() {
      throw new Error("not implemented");
    };

    iRepository.prototype.exec = function(callback) {
      throw new Error("not implemented");
    };

    return iRepository;

  })();

  module.exports = iRepository;

}).call(this);

//# sourceMappingURL=iRepository.js.map
