// Generated by CoffeeScript 1.11.0
(function() {
  var OrientDbRepository,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  OrientDbRepository = (function() {
    function OrientDbRepository(config) {
      this.config = config;
      this.exec = bind(this.exec, this);
      this.set = bind(this.set, this);
      this.setEdge = bind(this.setEdge, this);
    }

    OrientDbRepository.prototype.find = function(example, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.run = function(cypher, data, callback) {
      if (callback == null) {
        callback = null;
      }
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.get = function(example, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.index = function(nodesType, query, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.add = function(cypher, callback) {
      throw new Error('not implemented');
    };

    OrientDbRepository.prototype.indexEdge = function(edgesType, query, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.getEdge = function(example, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.setEdge = function(params, edge, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.set = function(id, obj, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.deleteEdge = function(edgeid, edgekind, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype["delete"] = function(nodeid, nodekind, callback) {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.pipeline = function() {
      throw new Error("not implemented");
    };

    OrientDbRepository.prototype.exec = function(callback) {
      throw new Error("not implemented");
    };

    return OrientDbRepository;

  })();

  module.exports = OrientDbRepository;

}).call(this);

//# sourceMappingURL=OrientDbRepository.js.map
