// Generated by CoffeeScript 1.10.0
(function() {
  var iImport;

  iImport = (function() {
    function iImport(config) {
      this.config = config;
    }

    iImport.prototype.query = function(context, repo, callback) {
      throw new Error("not implemented");
    };

    return iImport;

  })();

}).call(this);

//# sourceMappingURL=iQuery.js.map
