// Generated by CoffeeScript 1.10.0
(function() {
  var Neo4jRepostitory, assert, config, repo, repoConfig, should;

  should = require('should');

  assert = require('assert');

  config = require('../config/configuration');

  Neo4jRepostitory = require('../source/repositories/Neo4jRepository');

  repoConfig = {
    url: config.neo4jurl
  };

  repo = new Neo4jRepostitory(repoConfig);

  describe('Delete Graph', function() {
    var deleteGraph;
    deleteGraph = function(done) {
      console.log("Delete edges");
      repo.run("MATCH ()-[r]->() DELETE r", {}, function(error, result) {
        console.log("Delete nodes");
        if (error == null) {
          repo.run("MATCH (n) delete n", {}, function(error, result) {
            console.log("delete completed");
            return done();
          });
        }
      });
    };
    return it('deleting graph', function(done) {
      return deleteGraph(function() {
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=delete_graph.js.map
