// Generated by CoffeeScript 1.10.0
(function() {
  var Neo4jRepostitory, Papa, assert, async, config, fs, repo, repoConfig, should;

  should = require('should');

  assert = require('assert');

  async = require('async');

  Neo4jRepostitory = require('../source/repositories/Neo4jRepository');

  fs = require('fs');

  Papa = require('babyparse');

  config = require('../config/configuration');

  repoConfig = {
    url: config.neo4jurl
  };

  repo = new Neo4jRepostitory(repoConfig);

  describe('Import Relationships', function() {
    var runtest;
    runtest = function(testImport, callback) {
      var importer;
      console.log("import" + testImport.importer);
      importer = require(testImport.importer);
      importer["import"](testImport.source, repo, function(error, results) {
        if ((error != null)) {
          console.log(error);
          assert(false);
        }
        callback(error, results);
      });
    };
    it('wireup Product To Sellers', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupProductToSellers',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/sku-seller.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Product To Warehouses', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupProductToWarehouses',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/sku-bdwp.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Resupplier To Warehouses', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupResupplierToWarehouses',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/superdc-bdwp.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Seller To Warehouses', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupSellerToWarehouses',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/seller-bdwp.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Warehouse To Satellites', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupWarehouseToSatellites',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/satellite-bdwp.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Warehouse To Zones', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupWarehouseToZones',
        source: 'https://s3-us-west-1.amazonaws.com/bd-ne04j/Node-ZipRadius.csv'
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    it('wireup Sellers To GlobalZone', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupSellersToGlobalZone',
        source: null
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
    return it('wireup Warehouses To GlobalZone', function(callback) {
      var importer;
      importer = {
        importer: '../source/wireupWarehousesToGlobalZone',
        source: null
      };
      runtest(importer, function(error, result) {
        callback(error, result);
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_wireup_edges.js.map
