// Generated by CoffeeScript 1.10.0
(function() {
  var Importer, fs, iImport,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  iImport = require('./iImport');

  fs = require('fs');

  Importer = (function(superClass) {
    extend(Importer, superClass);

    function Importer(config) {
      this.config = config != null ? config : {};
    }

    Importer.prototype["import"] = function(source, repo, callback) {
      var query;
      if ((source != null)) {
        query = "USING PERIODIC COMMIT 1000 ";
        query += "LOAD CSV WITH HEADERS FROM '" + source + "' AS line ";
        query += this.config.cypher;
        repo.run(query, {}, (function(_this) {
          return function(error, result) {
            if ((error != null)) {
              console.log("" + JSON.stringify(error));
              callback(error, null);
            } else {
              callback(null, result);
            }
          };
        })(this));
      } else {
        repo.run(this.config.cypher, {}, (function(_this) {
          return function(error, result) {
            if ((error != null)) {
              console.log("" + JSON.stringify(error));
              callback(error, null);
            } else {
              callback(null, result);
            }
          };
        })(this));
      }
    };

    return Importer;

  })(iImport);

  module.exports = Importer;

}).call(this);

//# sourceMappingURL=ImportFromCSV.js.map
