// Generated by CoffeeScript 1.10.0
(function() {
  var Importer, config, importer;

  Importer = require('./importers/ImportNodeFromCSV');

  config = {
    cypher: "CREATE (:Warehouse {warehouseId:line.WarehouseId,pimcorewarehouseid:line.PIMCoreWarehouseID,postalcode:line.PostalCode,name:line.Name,issuperdc:line.isSuperDC})"
  };

  importer = new Importer(config);

  module.exports = importer;

}).call(this);

//# sourceMappingURL=importWarehouses.js.map
