// Generated by CoffeeScript 1.10.0
(function() {
  var Importer, config, importer;

  Importer = require('./importers/ImportFromCSV');

  config = {
    cypher: "MATCH (b:Warehouse {id:line.BDWPWarehouseID}),(s:Satellite {id:line.SatelliteWarehouseID}) CREATE (b)-[:FLOWS_THROUGH{ sellerCost:line.sellercost, leadTime:line.leadtime, bdCost:line.bdcost, custCost:line.custcost, id:b.id+'_'+s.id }]->(s)"
  };

  importer = new Importer(config);

  module.exports = importer;

}).call(this);

//# sourceMappingURL=wireupWarehouseToSatellites.js.map
