// Generated by CoffeeScript 1.10.0
(function() {
  var EdgeSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  EdgeSchema = new Schema({
    id: String,
    type: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Edge", EdgeSchema),
    schema: EdgeSchema
  };

}).call(this);

//# sourceMappingURL=edge.js.map
