// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, ObjectId, PathSchema, RouteSchema, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  PathSchema = new Schema({}, {
    strict: false,
    _id: false
  });

  RouteSchema = new Schema({
    to: String,
    skus: [String],
    routes: [PathSchema]
  }, {
    strict: true
  });

  module.exports = {
    model: Mongoose.model("Route", RouteSchema),
    schema: RouteSchema
  };

}).call(this);

//# sourceMappingURL=route.js.map
